# Generated by Django 3.2.5 on 2021-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
